name: Add to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/microsoft/projects/5010
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

  label_issues:
    name: Label issues
    runs-on: ubuntu-latest
    steps:
      - name: Label issue
        uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          include-title: true